default_context:
  project_name: 'EasyStart'
  project_slug: 'easystart'
  domain_main: '127.0.0.1'
  domain_staging: '127.0.0.1'
  docker_swarm_stack_name_main: '127-0-0-1'
  docker_swarm_stack_name_staging: '127-0-0-1'
  secret_key: '9ED36133223F152218156DB681A1D'
  first_superuser: 'admin@127.0.0.1'
  first_superuser_password: 'p@ssw@rd'
  backend_cors_origins: '["http:/localhost", "http://localhost:8080", "https:/localhost", "https://localhost:8080"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@127.0.0.1'
  postgres_password: 'passswo@'
  pgadmin_default_user: 'admin@127.0.0.1'
  pgadmin_default_user_password: 'p@ssw@rd'
  traefik_constraint_tag: '127.0.0.1'
  traefik_constraint_tag_staging: '127.0.0.1'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:p@ssw@rd'
  sentry_dsn: ''
  docker_image_prefix: 'smm'
  docker_image_backend: 'smmbackend'
  docker_image_celeryworker: 'smmceleryworker'
  docker_image_frontend: 'smmfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
